AvoidOutlineForSingleExample:
    Enabled: true
AvoidPeriod:
    Enabled: true
AvoidQuotes:
    Enabled: true
AvoidScripting:
    Enabled: false
BackgroundDoesMoreThanSetup:
    Enabled: true
BackgroundRequiresMultipleScenarios:
    Enabled: true
BadScenarioName:
    Enabled: true
BeDeclarative:
    Enabled: true
FileNameDiffersFeatureName:
    Enabled: false
MissingExampleName:
    Enabled: true
MissingFeatureDescription:
    Enabled: false
MissingFeatureName:
    Enabled: true
MissingScenarioName:
    Enabled: true
MissingTestAction:
    Enabled: true
MissingVerification:
    Enabled: true
InvalidFileName:
    Enabled: true
InvalidStepFlow:
    Enabled: true
PreziAvoidCharsInOutline:
    Enabled: true
PreziAvoidQuotes:
    Enabled: true
PreziAvoidStepsContaining:
    Enabled: true
PreziFeatureSwitchInsideFeature:
    Enabled: true
PreziFSOnSeparateLines:
    Enabled: true
PreziTagsFeatureSwitchOrder:
    Enabled: true
PreziUseGivenWhenThenOnce:
    Enabled: true
PreziMissingPlatformTag:
      Enabled: true
PreziMissingTeamTag:
      Enabled: true
PreziTagsInsideFeature:
    Enabled: true
PreziTagsOnSeparateLines:
    Enabled: true
RequiredTagsStartsWith:
    Enabled: false
SameTagForAllScenarios:
    Enabled: true
TagUsedMultipleTimes:
    Enabled: true
TooClumsy:
    Enabled: false
TooManyDifferentTags:
    Enabled: false
TooManySteps:
    Enabled: true
TooManyTags:
    Enabled: true
TooLongStep:
    Enabled: true
UniqueScenarioNames:
    Enabled: true
UnknownVariable:
    Enabled: true
UnusedVariable:
    Enabled: true
UseBackground:
    Enabled: true
UseOutline:
    Enabled: false
