AvoidCharsInOutline:
    Enabled: true
AvoidOutlineForSingleExample:
    Enabled: true
AvoidPeriod:
    Enabled: true
AvoidStepsContaining:
    Enabled: true
AvoidQuotes:
    Enabled: true
AvoidScripting:
    Enabled: false
BackgroundDoesMoreThanSetup:
    Enabled: true
BackgroundRequiresMultipleScenarios:
    Enabled: true
BadScenarioName:
    Enabled: true
BeDeclarative:
    Enabled: true
FeatureSwitchInsideFeature:
    Enabled: true
FileNameDiffersFeatureName:
    Enabled: false
FSOnSeparateLines:
    Enabled: true
MissingExampleName:
    Enabled: true
MissingFeatureDescription:
    Enabled: false
MissingFeatureName:
    Enabled: true
MissingScenarioName:
    Enabled: true
MissingPlatformTag:
      Enabled: true
MissingTeamTag:
      Enabled: true
MissingTestAction:
    Enabled: true
MissingVerification:
    Enabled: true
InvalidFileName:
    Enabled: true
InvalidStepFlow:
    Enabled: true
RequiredTagsStartsWith:
    Enabled: false
SameTagForAllScenarios:
    Enabled: true
TagsFeatureSwitchOrder:
    Enabled: true
TagsInsideFeature:
    Enabled: true
TagsOnSeparateLines:
    Enabled: true
TagUsedMultipleTimes:
    Enabled: true
TooClumsy:
    Enabled: false
TooManyDifferentTags:
    Enabled: false
TooManySteps:
    Enabled: true
TooManyTags:
    Enabled: true
TooLongStep:
    Enabled: true
UniqueScenarioNames:
    Enabled: true
UnknownVariable:
    Enabled: true
UnusedVariable:
    Enabled: true
UseBackground:
    Enabled: true
UseGivenWhenThenOnce:
    Enabled: true
UseOutline:
    Enabled: false
